from enum import Enum


class Constants:
    # True/False,
    #   if True, overwrites files in output path if they already exist.
    OVERWRITE_MODE = False

    # Regex for common prefixes to get code.
    CODE_REGEX = '^\d\d\d'

    # True/False,
    #   if True, mixes faces background (works sloppy with hair),
    #   if False, all background is transparent.
    MIX_BACKGROUNDS = False

    # Integer,
    #   how many morphing levels should be generated
    #   (>=3, since the first (0%) and the last (100%) levels will be skipped).
    MORPHING_LEVELS = 11

    # Possible image extensions.
    #   Not sure that you can add something more to this.
    IMAGE_EXTENSIONS = ('.png', '.jpg', 'jpeg')

    # Integer,
    #   Size of resulting pictures generated by facemorpher, in pixels.
    MORPHING_RESULT_HEIGHT = 600
    MORPHING_RESULT_WIDTH = 500

    # Integer,
    #   2<=x<=100, how many fragments of face picture will be scrambled.
    SCRAMBLING_SQUARES_VERTICAL = 10
    SCRAMBLING_SQUARES_HORIZONTAL = 10

    # Float,
    #   0 < x < 1, noise level (standard deviation of normal distribution).
    NOISE_LEVEL = 0.7


# Person and mood tags used in pictures naming.
class Person(Enum):
    YOURSELF = 'I'
    FRIEND = 'f'
    STRANGER = 's'


class Mood(Enum):
    HAPPY = 'h'
    NORMAL = 'n'
    SAD = 's'
